version: '3.8'

services:
  frontend:
    image: ghcr.io/fix2015/quize-game-webapp/frontend:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3013:80"

networks:
  default:
    driver: bridge
